name: Richard Perry
description: Just another blog about nothing

markdown: kramdown
pygments: true
exclude: 
- 'Vagrantfile'
- '.vagrant'
- 'changes'
- 'Gemfile'
- 'Gemfile.lock'
- 'params.json'
- 'deploy.sh'

encoding: utf-8

permalink: /:categories/:title/

paginate: 10
paginate_path: "page/:num"

author:
  name: Richard Perry
  email: richard@perrymail.me.uk
  github: richardp2
  twitter: richard_p2
  
images: /images
thumbs: /images/thumbs

prose:
  rooturl: '_posts'
  siteurl: 'http://richardp2.github.io/'
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
          placeholder: "Richard Perry"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          placeholder: "Choose Category"
          options:
            - name: "General"
              value: "general"
            - name: "Photography"
              value: "photography"
            - name: "George"
              value: "george"
            - name: "Languages"
              value: "languages"
            - name: "Reviews"
              value: "reviews"
      - name: "comments"
        field:
          element: checkbox
          label: "Comments"
          value: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
