name: Richard @ GitHub
markdown: redcarpet
pygments: true

permalink: /blog/:categories/:title/

paginate: 10
paginate_path: "blog/p:num"

redcarpet:
  extensions: [tables,autolink,smart,strikethrough,superscript]
    
    
author:
  name: Richard Perry
  email: richard@perrymail.me.uk
  github: richardp2
  twitter: richard_p2