# Site details
name:                Richard Perry
description:         Just another blog about nothing
owner:               richard
authors:             richard
url:                 http://richard.perry-online.me.uk
email:               richard@perry-online.me.uk

# Where things are
images:              /assets/images
thumbs:              /assets/images/thumbs

# Handling Reading
exclude: 
  - 'changes'
  - 'CNAME'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE.md'
  - 'README.md'

# Plugins
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions
  - jemoji

# Outputting
permalink:           /:title/
paginate:            10
paginate_path:       "page/:num"
timezone:            Europe/London
defaults:
  -
    scope:
      path:          ""
      type:          "posts"
    values:
      layout:        "post"
      comments:      true
  -
    scope:
      path:          "pages"
    values:
      layout:        "page"
      comments:      false

# Markdown Processors
kramdown:
  enable_coderay:       true

sass:
  style:             compressed

# Tag Config
tag_names:
  epic quest: 
    name:            Epic Quest
    link:            epic
  
# Comments
comments:
  disqus:
    shortname: richardperry
  facebook :
    id: 286603693
    appid : 181763705182339
    num_posts: 10
    width: 100%
    colorscheme: light


