name: Richard @ GitHub
markdown: redcarpet
pygments: true
baseurl: richardp2.github.io

permalink: /blog/:categories/:title.html

paginate: 10
paginate_path: "blog/p:num"

redcarpet:
    extensions: [tables,autolink,smart]