name: Richard @ GitHub
markdown: rdiscount
pygments: true

permalink: /blog/:categories/:title/

paginate: 10
paginate_path: "blog/p:num"

    
    
author:
  name: Richard Perry
  email: richard@perrymail.me.uk
  github: richardp2
  twitter: richard_p2