# Site details
name:                Richard Perry
description:         Just another blog about nothing
author:               richard
authors:             richard
url:                 http://richard.perry-online.me.uk
email:               richard@perry-online.me.uk
logo:                true
hosting:
  name:              GitLab Pages
  link:              //gitlab.com

# Where things are
images:              /assets/images
thumbs:              /assets/images/thumbs

# Handling Reading
exclude: 
  - 'changes'
  - 'CNAME'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE.md'
  - 'README.md'

# Plugins
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-seo-tag
  #- jekyll-feed
  #- jekyll-sitemap

flickr:
  enabled:           yes
  use_cache:         true
  screen_name:       "Richard Perry"
  cache_dir:         ./_cache/flickr
  api_key:           4389a0eb79c41ca17e149830c22fc7c2
  api_secret:        ef41108edae962b0
  shared_secret:     ef41108edae962b0
  access_token:      72157641557984045-92a5dbebf3e01418
  access_secret:     1625dbdd3cf26db6

# Outputting
permalink:           /:title/
paginate:            10
paginate_path:       "page/:num"
timezone:            Europe/London
defaults:
  -
    scope:
      path:          ""
      type:          "posts"
    values:
      layout:        "post"
      comments:      true
  -
    scope:
      path:          "pages"
    values:
      layout:        "page"
      comments:      false

# Markdown Processors
sass:
  sass_dir:          _sass
#  style:             compressed
  style:             expanded

# Tag Config
tag_names:
  Epic Quest: 
    name:            Epic Quest
    link:            epic
  "Xi'an":
    name:         Xi'An
    link:         xi-an
  LOTR:
    name:         Lord of the Rings
    link:         lotr

# Comments
disqus:
  shortname:      richardperry

# Social
facebook:
  app_id:         181763705182339
  admins:         286603693
  num_posts:      10
  width:          100%
  colorscheme:    light

twitter:
  username:       richard_p2

social:
  links:
    - https://twitter.com/richard_p2
    - https://www.facebook.com/richardpperry
    - https://www.linkedin.com/in/rpperry
    - https://plus.google.com/+RichardPerry1
    - https://github.com/richardp2

