name: Richard Perry
description: Just another blog about nothing

markdown: kramdown
pygments: true
exclude: 
- 'changes'
- 'Gemfile'
- 'Gemfile.lock'
- 'params.json'
- 'Rakefile'
- 'README.md'

encoding: utf-8

permalink: /:categories/:title/
relative_permalinks: false

paginate: 10
paginate_path: "page/:num"

author:
  name: Richard Perry
  email: richard@perrymail.me.uk
  flickr: richard-perry
  github: richardp2
  twitter: richard_p2
  facebook: richardpperry
  linkedin: richard-perry-mrics
  instagram: perryri
  
images: /assets/images
thumbs: /assets/images/thumbs

category_dir: /

flickr:
  enabled:         yes
  cache_dir:       ./_cache/flickr
  api_key:         4389a0eb79c41ca17e149830c22fc7c2
  shared_secret:   ef41108edae962b0
  access_token:    72157641557984045-92a5dbebf3e01418
  access_secret:   1625dbdd3cf26db6


prose:
  rooturl: '_posts'
  siteurl: 'http://richardp2.github.io/'
  media: 'assets/images'
  metadata:
    _posts:
      - name: "blog"
        field:
          element: "select"
          label: "Blog"
          options:
            - name: "Richard Perry"
              value: "richard"
            - name: "Rosie & Jim's Travel Blog"
              value: "travel"
            - name: "Rosie & Jim's Photo Gallery"
              value: "photo"
      - name: "comments"
        field:
          element: checkbox
          label: "Comments"
          value: "true"
      - name: "date"
        field:
          element: hidden
          value: "2014-01-01 14:15:44+00:00"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          options:
            - name: "Post"
              value: "post"
            - name: "Image"
              value: "image"
            - name: "Gallery"
              value: "gallery"
            - name: "Link"
              value: "link"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "category"
        field:
          element: "multiselect"
          label: "Category"
          placeholder: "Choose Category"
          options:
            - name: "General"
              value: "General"
            - name: "Photography"
              value: "Photography"
            - name: "Instagram"
              value: "Instagram"
            - name: "George"
              value: "George"
            - name: "Languages"
              value: "Languages"
            - name: "Mandarin"
              value: "Mandarin"
            - name: "Reviews"
              value: "Reviews"
      - name: "flickimg"
        field:
          element: "text"
          label: "Flickr Thumbnail"
          value: ""
      - name: "photoset"
        field:
          element: "text"
          label: "Flickr Photoset"
          value: ""
      - name: "images"
        field:
          element: "number"
          label: "Number of images in Flickr Photoset"
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
