name: Richard Perry
description: Just another blog about nothing

destination: ../master
markdown: kramdown
pygments: true
exclude: 
- 'Vagrantfile'
- '.vagrant'
- 'changes'
- 'Gemfile'
- 'Gemfile.lock'
- 'params.json'
- 'deploy.sh'

encoding: utf-8

permalink: /:categories/:title/

paginate: 10
paginate_path: "page/:num"

author:
  name: Richard Perry
  email: richard@perrymail.me.uk
  emailo: r&#105;char%64&#64;p%65%&#55;2r&#37;&#55;9mai&#108;&#46;&#109;e&#46;u&#107;
  flickr: richard-perry
  github: richardp2
  twitter: richard_p2
  facebook: richardpperry
  linkedin: richard-perry-mrics
  instagram: perryri
  
images: /assets/images
thumbs: /assets/images/thumbs

category_dir: /


flickr:
  enabled:         yes
  cache_dir:       ./_cache/flickr
  api_key:         4389a0eb79c41ca17e149830c22fc7c2
  shared_secret:   ef41108edae962b0
  access_token:    72157641557984045-92a5dbebf3e01418
  access_secret:   1625dbdd3cf26db6


prose:
  rooturl: '_posts'
  siteurl: 'http://richardp2.github.io/'
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
          placeholder: "Richard Perry"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          placeholder: "Choose Category"
          options:
            - name: "General"
              value: "general"
            - name: "Photography"
              value: "photography"
            - name: "George"
              value: "george"
            - name: "Languages"
              value: "languages"
            - name: "Reviews"
              value: "reviews"
      - name: "comments"
        field:
          element: checkbox
          label: "Comments"
          value: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
