# Site details
name: Richard Perry
description: Just another blog about nothing
owner: richard
authors: richard
url: http://richard.perry-online.me.uk
email: richard@perry-online.me.uk

# Where things are
images: /assets/images
thumbs: /assets/images/thumbs

# Handling Reading
exclude: 
- 'changes'
- 'Gemfile'
- 'Gemfile.lock'
- 'Gruntfile.js'
- 'node_modules'
- 'package.json'
- 'Rakefile'
- 'README.md'

# Plugins
gems:
- jekyll-mentions
- jemoji


flickr:
  enabled:         yes
  cache_dir:       ./_cache/flickr
  api_key:         4389a0eb79c41ca17e149830c22fc7c2
  shared_secret:   ef41108edae962b0
  access_token:    72157641557984045-92a5dbebf3e01418
  access_secret:   1625dbdd3cf26db6

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: "page/:num"

# Markdown Processors
kramdown:
  use_coderay: true

sass:
  style: compressed

# Category Config
category_names:
  epic quest: 
    name: Epic Quest
    link: epic
  


